-- MySQL Script generated by MySQL Workbench
-- Sun Mar  3 01:13:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tornasol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tornasol` ;

-- -----------------------------------------------------
-- Schema tornasol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tornasol` DEFAULT CHARACTER SET utf8 ;
USE `tornasol` ;

-- -----------------------------------------------------
-- Table `tornasol`.`estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`estacion` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`estacion` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estacion`),
  UNIQUE INDEX `id_estacion_UNIQUE` (`id_estacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`mecanismo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`mecanismo` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`mecanismo` (
  `id_mecanismo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mecanismo`),
  UNIQUE INDEX `id_mecanismo_UNIQUE` (`id_mecanismo` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`mes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`mes` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`mes` (
  `id_mes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_estacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mes`, `id_estacion`),
  INDEX `fk_mes_estacion1_idx` (`id_estacion` ASC) VISIBLE,
  CONSTRAINT `fk_mes_estacion1`
    FOREIGN KEY (`id_estacion`)
    REFERENCES `tornasol`.`estacion` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`ubicacion` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`ubicacion` (
  `id_ubicacion` INT NOT NULL AUTO_INCREMENT,
  `id_mes` INT UNSIGNED NOT NULL,
  `id_estacion` INT NOT NULL,
  `pos_x` INT NOT NULL,
  `pos_y` INT NOT NULL,
  `fecha_inicio` CHAR(5) NOT NULL,
  `fecha_fin` CHAR(5) NOT NULL,
  `orientacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ubicacion`, `id_mes`, `id_estacion`),
  UNIQUE INDEX `id_ubicacion_UNIQUE` (`id_ubicacion` ASC) VISIBLE,
  INDEX `fk_ubicacion_mes1_idx` (`id_mes` ASC, `id_estacion` ASC) VISIBLE,
  CONSTRAINT `fk_ubicacion_mes1`
    FOREIGN KEY (`id_mes` , `id_estacion`)
    REFERENCES `tornasol`.`mes` (`id_mes` , `id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`bateria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`bateria` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`bateria` (
  `id_bateria` INT NOT NULL AUTO_INCREMENT,
  `id_mecanismo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `voltaje_max` DOUBLE NOT NULL,
  `voltaje_min` DOUBLE NOT NULL,
  `nu_celdas` INT NOT NULL,
  `temperatura_max` DOUBLE NOT NULL,
  `hasMemoria` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_bateria`, `id_mecanismo`),
  INDEX `fk_bateria_mecanismo1_idx` (`id_mecanismo` ASC) VISIBLE,
  CONSTRAINT `fk_bateria_mecanismo1`
    FOREIGN KEY (`id_mecanismo`)
    REFERENCES `tornasol`.`mecanismo` (`id_mecanismo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`panel solar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`panel solar` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`panel solar` (
  `id_panel` INT NOT NULL AUTO_INCREMENT,
  `id_mecanismo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `voltaje_max` DOUBLE NOT NULL,
  `corriente_max` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_panel`, `id_mecanismo`),
  INDEX `fk_panel solar_mecanismo1_idx` (`id_mecanismo` ASC) VISIBLE,
  CONSTRAINT `fk_panel solar_mecanismo1`
    FOREIGN KEY (`id_mecanismo`)
    REFERENCES `tornasol`.`mecanismo` (`id_mecanismo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`historial_bateria_panel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`historial_bateria_panel` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`historial_bateria_panel` (
  `id_bateria` INT NOT NULL,
  `id_panel` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  INDEX `fk_descarga_bateria_bateria1_idx` (`id_bateria` ASC) VISIBLE,
  INDEX `fk_historial_bateria_panel_panel solar1_idx` (`id_panel` ASC) VISIBLE,
  CONSTRAINT `fk_descarga_bateria_bateria1`
    FOREIGN KEY (`id_bateria`)
    REFERENCES `tornasol`.`bateria` (`id_bateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_bateria_panel_panel solar1`
    FOREIGN KEY (`id_panel`)
    REFERENCES `tornasol`.`panel solar` (`id_panel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`sensadoP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`sensadoP` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`sensadoP` (
  `id_sensado_p` INT NOT NULL AUTO_INCREMENT,
  `id_panel` INT NOT NULL,
  `hora` DATETIME NOT NULL,
  `voltaje` DOUBLE NOT NULL,
  PRIMARY KEY (`id_sensado_p`, `id_panel`),
  INDEX `fk_sensadoP_panel solar1_idx` (`id_panel` ASC) VISIBLE,
  CONSTRAINT `fk_sensadoP_panel solar1`
    FOREIGN KEY (`id_panel`)
    REFERENCES `tornasol`.`panel solar` (`id_panel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`sensadoB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`sensadoB` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`sensadoB` (
  `id_sensado_b` INT NOT NULL AUTO_INCREMENT,
  `id_bateria` INT NOT NULL,
  `hora` DATETIME NOT NULL,
  `voltaje` DOUBLE NOT NULL,
  `corriente` DOUBLE NOT NULL,
  `temperatura` DOUBLE NOT NULL,
  PRIMARY KEY (`id_sensado_b`, `id_bateria`),
  INDEX `fk_sensadoB_bateria1_idx` (`id_bateria` ASC) VISIBLE,
  CONSTRAINT `fk_sensadoB_bateria1`
    FOREIGN KEY (`id_bateria`)
    REFERENCES `tornasol`.`bateria` (`id_bateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`estado_fase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`estado_fase` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`estado_fase` (
  `id_estado_fase` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_fase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`fase_bateria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`fase_bateria` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`fase_bateria` (
  `id_fase_bateria` INT NOT NULL AUTO_INCREMENT,
  `id_estado_fase` INT NOT NULL,
  `corriente` DOUBLE NOT NULL,
  PRIMARY KEY (`id_fase_bateria`, `id_estado_fase`),
  INDEX `fk_fase_bateria_estado_fase1_idx` (`id_estado_fase` ASC) VISIBLE,
  CONSTRAINT `fk_fase_bateria_estado_fase1`
    FOREIGN KEY (`id_estado_fase`)
    REFERENCES `tornasol`.`estado_fase` (`id_estado_fase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornasol`.`bateria_fase_bateria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornasol`.`bateria_fase_bateria` ;

CREATE TABLE IF NOT EXISTS `tornasol`.`bateria_fase_bateria` (
  `id_bateria` INT NOT NULL,
  `id_fase_bateria` INT NOT NULL,
  PRIMARY KEY (`id_bateria`, `id_fase_bateria`),
  INDEX `fk_bateria_has_fase_bateria_fase_bateria1_idx` (`id_fase_bateria` ASC) VISIBLE,
  INDEX `fk_bateria_has_fase_bateria_bateria1_idx` (`id_bateria` ASC) VISIBLE,
  CONSTRAINT `fk_bateria_has_fase_bateria_bateria1`
    FOREIGN KEY (`id_bateria`)
    REFERENCES `tornasol`.`bateria` (`id_bateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bateria_has_fase_bateria_fase_bateria1`
    FOREIGN KEY (`id_fase_bateria`)
    REFERENCES `tornasol`.`fase_bateria` (`id_fase_bateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
